import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

import localFont from "next/font/local";

// Define the font
const customFont = localFont({
  src: [
    {
      path: "../public/fonts/Satoshi-Black.woff2",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-custom", // CSS variable name
});

import { Space_Grotesk } from "next/font/google";

// Load Space Grotesk and assign a CSS variable
const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["400", "700"], // Add required font weights
  variable: "--font-space-grotesk", // Create a CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${customFont.variable}`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${customFont.variable} ${spaceGrotesk.className}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
